config/routes.rb
Rails.application.routes.draw do
 
 devise_for :users

 resources :users do
 	resources :likes
 end

 resources :places do
 	resources :likes 
 end

 root to: "static_pages#landing_page"

get '/landing_page', to: 'static_pages#landing_page'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :user_id, uniqueness: { scope: :place_id }

end

app/models/place.rb
class Place < ApplicationRecord
  
  	validates :name, :description, :image, presence: true
	validates :name, uniqueness: true
	validates :image, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
	    message: 'Must be a gif, jpg or png image!' }

mount_uploader :image, ImageUploader

belongs_to :user, :optional => true

has_many :likes, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :places
  has_many :likes, dependent: :destroy
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_sanitized_parameters, if: :devise_controller?

  def configure_sanitized_parameters
	devise_parameter_sanitizer.permit(:sign_up) do |user_params|
	  user_params.permit(:name, :email, :password, :password_confirmation)
	end

	devise_parameter_sanitizer.permit(:sign_in) do |user_params|
	  user_params.permit(:name, :email, :password, :password_confirmation)
	end

	devise_parameter_sanitizer.permit(:account_update) do |user_params|
		user_params.permit(:name, :email, :password, :password_confirmation, :current_password)
	end
end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


 skip_before_action :verify_authenticity_token
 before_action :authenticate_user!
 before_action :find_place, only: [:create, :destroy]
 


  def create
	@like = current_user.likes.build(user_id: current_user.id)
	@like.place_id = params[:place_id]
	  if !user_signed_in?
    redirect_to new_user_session_path
     end
     if current_user
	@like.save
	flash[:success] = 'Liked!'
redirect_to place_path(@place)
     end
  end

def liked?
  Like.where(user_id: current_user.id, place_id:
  params[:place_id]).exists?
end

  def destroy
 	@like = current_user.likes.build(user_id: current_user.id)
	@like.place_id = params[:place_id]
  	if !user_signed_in?
    redirect_to new_user_session_path
    end
   	if !liked?
  	flash[:notice] = 'Like first!'
      else
    @like.destroy
    redirect_to place_path(@place)  
    end
   
  end
 
 def total_likes
 	place.likes.count
 end
 
 private 

 def find_place
  @place = Place.find(params[:place_id])
 end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
 before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
 before_action :set_place, only: [:show, :edit, :update, :destroy]
 skip_before_action :verify_authenticity_token

  def new
  	@place = Place.new
  end
  
   def show
  	@place = Place.find(params[:id])
   end
  
  def index
    @places = Place.paginate(:page => params[:page], :per_page => 20)
  end

  def create
   @place = current_user.places.build(place_params) 
     if !user_signed_in?
      redirect_to new_user_session_path
     end
  	respond_to do |format|
  	  if @place.save
        format.html { redirect_to places_url, notice: 'New place was created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  	 respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


    def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private 

 def set_place
  	@place = Place.find(params[:id])
  end

  def place_params
  	params.require(:place).permit(:name, :description, :image, :image_cache)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  	  @places = Place.paginate(:page => params[:page], :per_page => 20)
  	  @place = Place.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Places</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag('jquery.js') %>
    <%= javascript_include_tag('bootstrap.js') %>
    <meta charset="UTF-8">
    <meta name="description" content="tourism">
    <meta name="author" content="rghost">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="source/font-awesome-4.5.0/css/font-awesome.css">
	<link rel="shortcut icon" href="<%= asset_path 'favicon.png' %>">
  </head>

  <body>

    <!-- Header -->
<div class="allcontain">
	<div class="header">
			<ul class="givusacall">
				<li> mail us: miarhost@gmail.com </li>
			</ul>
			<ul class="logreg">
				        <% if !user_signed_in? %>
                     
        <li><span><%= link_to 'Register', new_user_registration_path %></span> | </li>
        <li><span><%= link_to 'Login', new_user_session_path %></span> | </li>
                        <% else %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %> | </li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>                               
                      <% end %>    
  		   </ul>
	</div>
	<!-- Navbar Up -->
	<nav class="topnavbar navbar-default topnav">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed toggle-costume" data-toggle="collapse" data-target="#upmenu" aria-expanded="false">
					<span class="sr-only"> Toggle navigaion</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand logo" href="#"><img src="<%= asset_path 'logo1.jpg' %>" alt="logo"></a>
			</div>	 
		</div>
		<div class="collapse navbar-collapse" id="upmenu">
			<ul class="nav navbar-nav" id="navbarontop">
				<li class="active"><a href="<%= root_path %>">HOME</a> </li>
				<li>
					
                    <a href="#" data-toggle="modal" data-target="#contact">CONTACT</a>
				</li>
			</ul>
		</div>
	</nav>
</div>
 <%= yield %>

   <div id="contact" tabindex="-1" role="dialog" aria-labelledby="Login"  class="modal">
       <div class="modal-content">
           <div class="modal-header">
                <div class="modal-body">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
                  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                  	<img style="border-radius: 30px; width: 370%" src="<%= asset_path 'hk.jpg' %>">
				    <div class="txthover">
					
						<div class="txtcontent">
							<div class="stars">
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
							</div>
							<div class="simpletxt">
								<h3 class="name">The Most Liked Places</h3>
								<p>TripAdvisor recently released its list of the most popular tourist attractions in the world.The list is part of TripAdvisor's Traveler's Choice awards, which highlight traveler favorites based on ratings and reviews.Here are the world's highest-rated landmarks.  </p>
	 						</div>
							<div class="stars2">
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
							</div>
						</div>
				</div>	 
			</div>
        </div>
      </div>
  </div>            
 </div>
   
  </body>
</html>

app/views/places/_form.html.erb
          <div class="forms">
            
               <p class="lead text-gray-light">Add a new place of your interest, <br>try to describe and add a picture</p>

               <%= form_for @place, html: { multipart: true } do |f| %>
             
 <% if place.errors.any? %>
  <div id="error explanation">
  <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

   <ul> 
    <% place.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>
              <div class="col-md-6">
                <%= f.label :name, 'A place is called:' %>
              <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
              </div>
               <div class="col-sm-6">
                <%= f.label :description, 'Say something about it:' %>
              <%=  f.text_field :description, placeholder: 'a fabulous city', class: 'form-control' %>
               </div>
              <div class="col-sm-6">
                <%= f.label :image, 'Add a photo:' %>
              <%= f.file_field :image %>
              <%= f.hidden_field :image_cache %>
               </div>
              
                  <div class="actions">
                 <%= f.button 'Submit', class: 'btn btn-primary', type: 'submit' %>
                 </div>
              
                 <% end %>
               </div>
       </div>

     <!--MODAL FORM END -->

app/views/places/_form1.html.erb
 <section class="form text-center no-padding-bottom">
        <div class="container">
          <div class="row">
             <div class="col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
               <p class="lead text-gray-light">Add a new place of your interest, try to describe and add a picture</p>

               <%= form_for @place  do |f| %>
             
 <% if place.errors.any? %>
  <div id="error explanation">
  <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

   <ul> 
    <% place.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
  </div>
 <% end %>
              <div class="col-md-12">
                <%= f.label :name, 'A place is called:' %>
              <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
              </div>
               <div class="col-md-12">
                <%= f.label :description, 'Say something about it:' %>
              <%=  f.text_field :description, placeholder: 'a fabulous city', class: 'form-control' %>
               </div>
              <div class="col-md-12">
                <%= f.label :image, 'Add a photo:' %>
              <%= f.file_field :image %>
              <%= f.hidden_field :image_cache %>
               </div>
                  <div class="actions">
                 <%= f.button 'Submit', class: 'btn btn-primary', type: 'submit' %>
                 </div>
                 <% end %>
               </div>
          </div> 
        </div>
<br>
    

app/views/places/_index.html.erb
<%= will_paginate @places %>
	<div class="grid">
		<div class="row">
<% @places.each do |place| %> 
<!-- ________________________UI STYLE FOR PLACE_______________-->



			<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
				<div class="txthover">
					<%= image_tag(place.image_url, version: :medium) if place.image? %>
						<div class="txtcontent">
							<div class="stars">
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
							</div>
							<div class="simpletxt">
								<h3 class="name"><%= place.name %></h3>
								<p><%= place.description.truncate(25) %><br>
	 							Come and visit it! </p>
	 							<%= link_to 'SEE MORE',place_path(place) %><br>
	 							<div class="wishtxt">
		 						     
		 							<%= link_to 'Like', place_likes_path(place), method: :post, remote: true, class: 'glyphicon glyphicon-heart' %>
		 							 <% if current_user %>
		 							    <%= link_to 'Unlike', place_like_url(place_id: place, id: current_user.id), method: :delete, class: 'glyphicon glyphicon-fire' %>
		 							  <% end %>
		 						</div>
							</div>
							<div class="stars2">
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
							</div>
						</div>
				</div>	 
			</div>

			<% end %>

		</div>
	</div>

app/views/places/_new.html.erb
         <div class="modal-dialog modal-col-md-offset-2"> 
          <div class="modal-content">
            <div class="modal-header">

                <div class="modal-body">
                	              <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
              <h4 class="modal-title text-center">Places</h4>
            
<%= render 'places/form', place: @place %>
<%= link_to 'Back', places_path %>
 </div>
 </div>
</div>
</div>


	

app/views/places/edit.html.erb
<h1>Editing PLace</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<%= will_paginate @places %>
	<div class="grid">
		<div class="row">
<% @places.each do |place| %> 
<!-- ________________________UI STYLE FOR PLACE_______________-->



			<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
				<div class="txthover">
					<%= image_tag(place.image_url, version: :medium) if place.image? %>
						<div class="txtcontent">
							<div class="stars">
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
							</div>
							<div class="simpletxt">
								<h3 class="name"><%= place.name %></h3>
								<p><%= place.description.truncate(25) %><br>
	 							Come and visit it! </p>
	 							<%= link_to 'SEE MORE',place_path(place) %><br>
	 							<div class="wishtxt">
		 						     
		 							<%= link_to 'Like', place_likes_path(place), method: :post, remote: true, class: 'glyphicon glyphicon-heart' %>
		 							 <% if current_user %>
		 							    <%= link_to 'Unlike', place_like_url(place_id: place, id: current_user.id), method: :delete, class: 'glyphicon glyphicon-fire' %>
		 							  <% end %>
		 						</div>
							</div>
							<div class="stars2">
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
								<div class="glyphicon glyphicon-star"></div>
							</div>
						</div>
				</div>	 
			</div>

			<% end %>

		</div>
	</div>

app/views/places/new.html.erb
<div class="col-md-12">
<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>
</div>

app/views/places/show.html.erb
	<div class="newslettercontent">
		     <div class="leftside">
<%= image_tag(@place.image.url, version: :medium) if @place.image? %>
                <h1><%= @place.name %></h1>
			    
		     </div>
             <div class="rightside">
             <p class="glyphicon glyphicon-heart"> Likes: <%= @place.likes.count %></p>
             <p>
  <%= link_to 'Edit', edit_place_path(@place) %> |
   <%= link_to 'Delete', @place, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', places_path %>
            </p>
             </div>
                     <div class="row d-flex align-items-stretch">
                        <div class="text col-md-5">
                             <h1><%= @place.name %></h1>
                                <p><%= @place.description %></p>
                            </div>
                        </div>
                    </div>
    </div>

app/views/static_pages/landing_page.html.erb
<div class="places">
	<h1 class="text-center">PLACES</h1>
	<ul class="nav nav-tabs navbar-left latest-navleft">
		<li role="presentation" class="li-sortby"><span class="sortby">							<% if !user_signed_in? %>
			    <a href="<%= new_user_registration_path %>" class="btn btn-primary">POST A NEW PLACE</a>
			    <% else %>
				<a href="#" data-toggle="modal" data-target="#create" class="btn btn-primary">POST A NEW PLACE</a>
				<% end %>
	    </li>
	</ul>
</div>
<br>
<br>
<%= render partial: 'places/index' %>

   <div id="create" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
              
       	<%= render 'places/new' %>
              
    </div>

<br>
<br>

 